# Generated by Django 3.1.5 on 2021-02-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likerecord',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likerecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='DislikeRecord',
        ),
        migrations.DeleteModel(
            name='LikeRecord',
        ),
    ]
