# Generated by Django 3.1.5 on 2021-01-24 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TieZi_Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='不超过20个字符', max_length=20, null=True, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='TieZi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='不超过40个字符', max_length=40, verbose_name='帖子标题')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_altered_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tiezi_label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiezi.tiezi_label')),
            ],
        ),
    ]
