# Generated by Django 3.1.5 on 2021-01-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiezi',
            options={'ordering': ['-created_time']},
        ),
    ]
