# Generated by Django 3.1.5 on 2021-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0002_auto_20210124_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiezi',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
