# Generated by Django 3.1.5 on 2021-01-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0003_tiezi_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiezi',
            name='read_num',
        ),
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
                ('tiezi', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tiezi.tiezi')),
            ],
        ),
    ]
