# Generated by Django 3.1.5 on 2021-01-28 06:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0005_delete_readnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiezi',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
