# Generated by Django 3.1.5 on 2021-02-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0007_auto_20210202_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiezi',
            name='tiezi_label',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tiezi.tiezi_label'),
        ),
    ]
