# Generated by Django 3.1.5 on 2021-02-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20210202_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='root',
        ),
        migrations.AddField(
            model_name='comment',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children_comment', to='comment.comment'),
        ),
    ]
